-- Role: db-inline
-- DROP ROLE "db-inline";

CREATE ROLE "db-inline" LOGIN
  ENCRYPTED PASSWORD 'md58d08d74be4a2ad8705805d55b122c723'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;

CREATE DATABASE "db-inline" WITH OWNER = "db-inline" ENCODING = 'UTF-8' CONNECTION LIMIT = -1 TEMPLATE template0;

GRANT ALL ON DATABASE "db-inline" TO "db-inline";
